spring.datasource.url=jdbc:postgresql://localhost:5432/izin_talep_sistemi
spring.datasource.username=your_db_username
spring.datasource.password=your_db_password

app.bootstrap-admin.email=admin@yourcompany.com
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD}

app.upload-dir=your_upload_direction_here